ARG BASE_IMAGE=metanorma/metanorma:windows-ltsc2025-1.16.6
ARG EENGINE_VERSION=5.2.7

FROM ${BASE_IMAGE}

# Install eengine (Windows x86-64)
RUN powershell -Command \
      "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
       Invoke-WebRequest -Uri 'https://github.com/expresslang/eengine-releases/releases/download/eeng-${EENGINE_VERSION}/eengine-${EENGINE_VERSION}-win-x86-64-sbcl.exe' -OutFile 'C:\Windows\eengine.exe'"

# Install eep (Windows x86)
RUN powershell -Command \
      "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
       Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/expresslang/eep-releases/main/windows/eep-windows-x86.exe' -OutFile 'C:\Windows\eep.exe'"

WORKDIR c:/metanorma
